# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_auto_20160103_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('1', 'One picture'), ('2', 'Two picture')], default='1', max_length=255),
        ),
    ]
