# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_photo_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
