# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_photo_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('1', 'One picture'), ('2', 'Two picture'), ('3', 'Full View')], default='1', max_length=255),
        ),
    ]
