# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_auto_20160515_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cropping',
        ),
    ]
