# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0003_home_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='pintrest',
            new_name='pinterest',
        ),
    ]
