# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='company_adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
