# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0008_auto_20160110_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_home', models.ImageField(upload_to='homesite/')),
            ],
        ),
    ]
